# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the 'â¯' symbol in the prompt with 'âŒ˜'
[character]
success_symbol = '[âŒ˜](bold bright-blue)'
error_symbol = '[âŒ˜](bold bright-red)'

# Disable stuff
[aws]
disabled = true

[package]
disabled = true

[gcloud]
disabled = true

[azure]
disabled = true

# Git
[git_branch]
symbol = 'ğŸŒ± '
style = 'bold green'

# Node
[nodejs]
symbol = 'ğŸ’© '
style = 'bold yellow'

# Battery
[battery]
full_symbol = 'ô€›¨  '
charging_symbol = 'ô€‹¦ '
discharging_symbol = 'ô€›ª  '
empty_symbol = 'ô€›ª  '
unknown_symbol = 'ô€›ª  '
